FREE_MODULES = {
    "argparse": True,
    # "array": True,
    "base64": True,
    # "collections": True,
    # "collections.abc": True,
    "contextlib": True,
    "csv": True,
    "datetime": True,
    "decimal": True,
    "enum": True,
    "fnmatch": True,
    "functools": True,
    "glob": True,
    "gzip": True,
    "hashlib": True,
    "http": True,
    "http.server": True,
    "itertools": True,
    "logging": True,
    "math": True,
    "mmap": True,
    "multiprocessing": True,
    "operator": True,
    "os": True,
    "pathlib": True,
    "pickle": True,
    "platform": True,
    "queue": True,
    "random": True,
    "re": True,
    "select": True,
    "shutil": True,
    "socket": True,
    "socketserver": True,
    "statistics": True,
    # "string": True,
    "sys": True,
    "sysconfig": True,
    "tempfile": True,
    "threading": True,
    "time": True,
    "traceback": True,
    # "types": True,
    "urllib": True,
    "uuid": True,
    "warnings": True,
    "xml": True,
    "zipfile": True,
    "zlib": True,
}
